### Particle Image Function
### Version: 1.0.4
### Width: 32
### Height: 32
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.75 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.625 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.625 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.5625 ~0 ~-0.4375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.5625 ~0 ~0.3125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.5 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.5 ~0 ~-0.0625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.5 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.5 ~0 ~0.0625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.5 ~0 ~0.1875 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.5 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.4375 ~0 ~-0.3125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.4375 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.4375 ~0 ~-0.0625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.4375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.4375 ~0 ~0.0625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.4375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.4375 ~0 ~0.3125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.4375 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.375 ~0 ~-0.3125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.375 ~0 ~0.3125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.3125 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.3125 ~0 ~-0.1875 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.3125 ~0 ~0.1875 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.3125 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.3125 ~0 ~0.3125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.3125 ~0 ~0.5625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.25 ~0 ~-0.4375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.25 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.25 ~0 ~0.4375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.1875 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.125 ~0 ~-0.6875 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.125 ~0 ~-0.4375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.125 ~0 ~-0.0625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.125 ~0 ~0.0625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.125 ~0 ~0.4375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.125 ~0 ~0.6875 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.0625 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.0625 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0.0625 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0 ~0 ~-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0 ~0 ~-0.6875 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0 ~0 ~-0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0 ~0 ~-0.5625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0 ~0 ~-0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0 ~0 ~-0.3125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0 ~0 ~-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0 ~0 ~-0.1875 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0 ~0 ~0.1875 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0 ~0 ~0.3125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0 ~0 ~0.5625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0 ~0 ~0.625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0 ~0 ~0.6875 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~0 ~0 ~0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.0625 ~0 ~-0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.0625 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.0625 ~0 ~0.375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.125 ~0 ~-0.0625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.125 ~0 ~0.0625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.1875 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.25 ~0 ~-0.4375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.25 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.25 ~0 ~0.4375 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.3125 ~0 ~-0.5625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.3125 ~0 ~-0.3125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.3125 ~0 ~-0.1875 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.3125 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.3125 ~0 ~0.1875 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.3125 ~0 ~0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.3125 ~0 ~0.3125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.3125 ~0 ~0.5625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.375 ~0 ~0.125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.375 ~0 ~0.3125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.4375 ~0 ~-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.4375 ~0 ~-0.3125 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.4375 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.4375 ~0 ~0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.5 ~0 ~-0.0625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.5 ~0 ~0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.5 ~0 ~0.0625 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.5,0.0,0.5],scale:1} ~-0.75 ~0 ~0 0 0 0 0 1 force @a
